### ISSUE TITLE
New Artwork

### ISSUE THREAD

**Issue by anxdpanic** [anxdpanic/plugin.video.composite_for_plex#100]
The current icon and fanart were created as a placeholders.

The artwork must meet the Plex [Trademarks and Guidelines](https://www.plex.tv/en-ca/about/privacy-legal/plex-trademarks-and-guidelines/)

**Comment by spooknik** [comment]
Just throwing two ideas out there. Might be too derivative.

 No idea what look you're going for, but let me know what you think. 

![logo-1](https://user-images.githubusercontent.com/40317809/76066969-e62e2500-5f8e-11ea-95f9-bf1b607840ec.png)
![logo-2](https://user-images.githubusercontent.com/40317809/76066973-e62e2500-5f8e-11ea-976b-19cb226e53bf.png)

**Comment by anxdpanic** [comment]
@spooknik 
I love both of these, the issue is I don't believe they fit with Plex's Trademark guidelines. My fault for not including this in the issue, very sorry about that.

https://www.plex.tv/en-ca/about/privacy-legal/plex-trademarks-and-guidelines/
Mainly,
```
You may not:

Copy the Plex look and feel of any Plex website (including the use of our distinct colour combinations, graphic designs or typography) or create any altered, distorted or interpreted representation of any of the Plex marks, as this could create confusion among our users.
```

Thank you very much for this, and again sorry I didn't make this clearer.

**Comment by spooknik** [comment]
Oh yea, fair enough I should have known

Well at any rate here's another go at it: 

![logo_b_1](https://user-images.githubusercontent.com/40317809/76104493-c0773f00-5fd3-11ea-9ba1-3bcbf129fb93.png)
![logo_b_2](https://user-images.githubusercontent.com/40317809/76104495-c10fd580-5fd3-11ea-8fd2-07c819c8360c.png)

**Comment by anxdpanic** [comment]
I really like those and would be very happy to add them. If there are any extras touches you'd like to make, I'd say go ahead.
Could the second image be made fanart size?
The icon needs to be 512x512 png, and fanart can be 3840x2160 png if size is small otherwise jpg. No transparency is allowed in either on the official repository.

Thank you very much for this, I'm about as artistic as a pet rock. :laughing:

**Comment by spooknik** [comment]
Glad you like it, I have no idea what you had in mind. Happy to contribute to the project in my own small way :)

I don't have any extra touches in mind right now, but maybe in the future someone will suggest something. 

Here's the icon in 512X512

![Composite_Logo](https://user-images.githubusercontent.com/40317809/76150214-2af9af00-60a8-11ea-8bd3-a868dfa0fa88.png)

And the fanart in 3840x2160. (It's under 100kb, so hopefully small enough)

![Composite_Fanart](https://user-images.githubusercontent.com/40317809/76150208-233a0a80-60a8-11ea-8cf3-2062c589c0b0.png)

**Comment by anxdpanic** [comment]
Honestly, I had no idea or expectations of what I had in mind either. Very happy with the result though, thank you again for the contribution! Time is tight this week but I should have them in the master branch tomorrow or Monday.

**Comment by anxdpanic** [comment]
Added with https://github.com/anxdpanic/plugin.video.composite_for_plex/commit/3be3f0e8870c8c3f3a1b9ededb61225cc52be235
Included in the beta, https://github.com/anxdpanic/plugin.video.composite_for_plex/releases/tag/1.0.0-dev
Thank you again!

**Comment by anxdpanic** [comment]
I've also added credit in the README.md in #137
I didn't @ in the readme because I'm not sure if that would cause you to be pinged every time the readme changes
