### ISSUE TITLE
Transcoding settings not honored

### ISSUE THREAD

**Issue by splitice** [anxdpanic/plugin.video.composite_for_plex#133]
I've set a transcoding profile in settings, I've even requested transcode always. Still direct plays (at a remote 47Mbps too!).

![](https://drive.google.com/a/x4b.net/uc?id=13rnA4SZKbcpuAFn7gTt70JFrrareyX02)

**Comment by splitice** [comment]
Also setting a remote stream limit in PMS just causes the stream to fail to start.

**Comment by anxdpanic** [comment]
So I can try to reproduce as closely as possible, what are you using for a transcode profile, kodi version and os?

**Comment by splitice** [comment]
It doesnt matter what settings, I've tested all combinations. It never has an effect.

Kodi and plugin are both latest stable taken directly from repositories. I'm away from home currently so I can't get the exact versions.

**Comment by anxdpanic** [comment]
All transcoding I tried seemed to work here.  

Will need a log with debug logging enabled. For this I suggest sanitizing the log first. search and replace any server ips with ```.```'s or ```-```'s, and any ```*Token=<token>```, the add-on hides this as best as possible but some leaks through with Kodi's logging. Feel free to email it to my gmail (same username) for further privacy.

**Comment by anxdpanic** [comment]
Please re-open this issue with the requested info, I've still been unable to reproduce.
