### ISSUE TITLE
HDR Tonemapping?

### ISSUE THREAD

**Issue by spooknik** [anxdpanic/plugin.video.composite_for_plex#135]
Hello! 

Love the Add-on plays 4K very smooth on Raspberry Pi 4 when the official Plex add-on can't. 

One small suggestion, would HDR tonemapping be a possible feature? I occasionally have HDR content that is being played on a non-HDR screen and it looks washed-out. I

I know the official Plex Media Player will tonemap to avoid this. 

Thanks for the great software 👍

**Comment by anxdpanic** [comment]
I don't think this is something I can achieve from the add-on. I will look into it more though. iirc, Kodi on Android has some sort of hdr support, but not sure it's ready for any other OS yet.

**Comment by spooknik** [comment]
All good, I totally understand if the support for HDR isn't there in the first place. I just thought if it was an easy change it would be a nice feature to have. 

Technically the most correct (and accurate) solutions is to have both SDR and HDR versions to begin with. 

Thanks for the reply :)
