### ISSUE TITLE
Global search

### ISSUE THREAD

**Issue by CorentinB** [anxdpanic/plugin.video.composite_for_plex#184]
Hi ! First, thanks for Composite, it works extremely well and I am confident that it will have a bright future.

I noticed there are ways to search in a specific library, but there is no way to do a global search across the libraries so far, or did I miss it?

Thanks!

**Comment by anxdpanic** [comment]
It's currently not exposed, but it is done in the add-on and could be exposed.

It's used for TraktToKodi and TheMovieDB Helper

Will try to have this added for the v1.4.0 release

**Comment by CorentinB** [comment]
Awesome. If I can add another thing too, I see there are 2 endpoints for search, one for episodes and one for movies, am I right if I say that the endpoint for searching shows is implemented but not exposed too?

**Comment by anxdpanic** [comment]
Searching shows should be available in any tv show section already.

alpha4 adds 'Combined Sections' to the main menu, you'll find global searches there, https://github.com/anxdpanic/plugin.video.composite_for_plex/releases/tag/1.x.x-dev

**Comment by anxdpanic** [comment]
This is part of 1.4.0, will be submitted to the official repository shortly. Also available https://github.com/anxdpanic/plugin.video.composite_for_plex/releases/tag/v1.4.0
