### ISSUE TITLE
Playback failed: One or more items failed to play

### ISSUE THREAD

**Issue by Sada-Mio** [anxdpanic/plugin.video.composite_for_plex#239]
### Context

* Add-on Version: 1.4.1+matrix.1
* Kodi Version: 19.1
* Operating System: Both WIN10 & Nvidia Shield android

------

### Expected Behavior

Open video. Close video. Open video again.

------

### Current Behavior

Open video after just closing fails with popup error "Playback failed: One or more items failed to play"

------

### Steps to Reproduce

* Install Kodi 19.1, 
* Install composite
* HTTP direct stream mode
* open video
* close video
* open same video
* get playback failed error.

**Comment by eloo** [comment]
Other plex plugins are affected as well
https://github.com/croneter/PlexKodiConnect/issues/1358
