### ISSUE TITLE
takes long time to load in big libraries

### ISSUE THREAD

**Issue by aniel300** [anxdpanic/plugin.video.composite_for_plex#269]
i have a 22k movie library and it takes long time to get into the "all movies" section, is it working as design? am happy to send long etc, thanks

**Comment by anxdpanic** [comment]
A library that size is likely to take quite a while to load, if you provide a debug log of loading, i can see if anything is going wrong cause abnormal delay though.

**Comment by aniel300** [comment]
will share in the future
