### ISSUE TITLE
Kodi crash selecting external subtitles 

### ISSUE THREAD

**Issue by rapteev** [anxdpanic/plugin.video.composite_for_plex#271]
Hi
Android tv on nvidia shield.
Kodi nexus rc2.
Latest composite version.

When a movie is playing if I try to select external subtitles from opensubtitles.org kodi crash and return to android tv home.
This behavior only happens with composite plugin. Any other plugin or library movies work perfectly using external subtitles.

**Comment by anxdpanic** [comment]
Re-open if this is still and issue on final release. Include a complete debug log.
