### ISSUE TITLE
Performance poor with large TV show libraries

### ISSUE THREAD

**Issue by dmarkey** [anxdpanic/plugin.video.composite_for_plex#93]
With large TV show libraries the add-on basically hangs up.

Perhaps implementing some cache layer would be a good idea?

**Comment by dmarkey** [comment]
BTW, I'm talking about specifically the `plugin://plugin.video.composite_for_plex/library/tvshows/` integration

**Comment by anxdpanic** [comment]
There is some basic caching, the problem is this endpoint doesn't benefit from this much. It's meant only for library imports and updates, which shouldn't happen frequently.

How are you using this endpoint?

**Comment by anxdpanic** [comment]
Can you try with v0.7.0, should be a drastic improvement

**Comment by dmarkey** [comment]
Seems to be better. tool about 3 minutes to open the list of TV shows.

Is the intention for kodi to scan these virtual directories?

I set off a scan, and 3 days later it was at "c" (assuming out of a-z)

**Comment by anxdpanic** [comment]
It is intended for scanning/importing to the Kodi library using local information only. Not all the add-on/Plex features will be available from the library, I believe some can be added in the future though. 

Large library scans generally do take quite a while, as a general comparison it takes < 10 seconds for me to open that endpoint and a library scan took ~3 hours

Now that the tv show hashing is simplified, it would also be possible to add a favorite.
`<favourite name="All TV Shows" thumb="special://home/addons/plugin.video.composite_for_plex/resources/media/icon.png">ActivateWindow(10025,&quot;plugin://plugin.video.composite_for_plex/library/tvshows/&quot;,return)</favourite>`

**Comment by splitice** [comment]
Navigation of a large library on my TV isn't too bad (room for improvement). What currently sucks in scanning, I figure it needs to in the future only look for changes (i.e like the Plex partial scan).
